// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czserjcxwtsaqpijuwyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6c2VyamN4d3RzYXFwaWp1d3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzQ3MzksImV4cCI6MjA2NDgxMDczOX0.C-ks36uX9soR400FdPcRhKv8F3qk9AGPT-WMV4Sdqyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);